#include <cstdio>

using namespace std;
int n,m,i,j,b[1030][1030],a[1030];
int main()
{
    freopen("cmlsc.in","r",stdin);
    freopen("cmlsc.out","w",stdout);
    scanf("%d%d",&n,&m);
    for(i=1;i<=n;i++)
        scanf("%d",&a[i]);
    for(i=1;i<=m;i++)
        scanf("%d",&b[i][0]);
    if(b[1][0]==a[1])
        b[1][1]=1;
    for(j=2;j<=n;j++)
        if(b[1][j-1]==1||b[1][0]==a[j])
            b[1][j]=1;
        else
            b[1][j]=0;
    for(i=2;i<=m;i++)
    {
        if(b[i][0]==a[1])
            b[i][1]=1;
        else
            b[i][1]=b[i-1][1];
        for(j=2;j<=n;j++)
        if(b[i][0]==a[j])
            b[i][j]=b[i-1][j-1]+1;
        else
        {
            if(b[i-1][j]>=b[i-1][j-1]&&b[i-1][j]>=b[i][j-1])
                b[i][j]=b[i-1][j];
            else
            if(b[i][j-1]>=b[i-1][j-1]&&b[i][j-1]>=b[i-1][j])
                b[i][j]=b[i][j-1];
            else
            if(b[i-1][j-1]>=b[i-1][j]&&b[i-1][j-1]>=b[i][j-1])
                b[i][j]=b[i-1][j-1];
        }
    }
    printf("%d\n",b[m][n]);
    i=m;
    j=n;
    while(b[i][j]!=0)
    {
        if(j==1)
        {
            if(b[i][j]!=b[i-1][j])
                a[b[i][j]]=b[i][0];
            i--;
        }
        else
        if(i==1)
        {
            if(b[i][j]!=b[i][j-1])
                a[b[i][j]]=b[i][0];
            j--;
        }
        if(b[i][j-1]==b[i][j]&&j-1>0)
            j--;
        else
        if(b[i-1][j]==b[i][j]&&i-1>0)
            i--;
        else
        if(b[i-1][j-1]==b[i][j]&&j-1>0&&i-1>0)
        {
            i--;
            j--;
        }
        else
        if(b[i-1][j-1]==b[i][j]-1&&j-1>0&&i-1>0)
        {
            a[b[i][j]]=b[i][0];
            i--;
            j--;
        }
    }
    for(i=1;i<=b[m][n];i++)
        printf("%d ",a[i]);
    return 0;
}
